"""French + English stop-word set — used to tell justified prose apart from table
rows (see ``extract_pdf._is_prose`` / ``_PROSE_DENSITY``).

Source: stopwords-iso (https://github.com/stopwords-iso), MIT-licensed. This is the
union of ``stopwords-fr`` and ``stopwords-en`` with pure-digit entries removed.

To refresh / extend:

    curl -fsSL https://raw.githubusercontent.com/stopwords-iso/stopwords-fr/master/stopwords-fr.txt > fr.txt
    curl -fsSL https://raw.githubusercontent.com/stopwords-iso/stopwords-en/master/stopwords-en.txt > en.txt
    # union + lowercase, drop any entry containing a digit, sort, regenerate below.

Or just add words to the set directly — it is a plain frozenset.
"""
STOPWORDS = frozenset({
    "'ll", "'tis", "'twas", "'ve", 'a', "a's", 'able', 'ableabout', 'abord', 'about', 'above',
    'abroad', 'absolument', 'abst', 'accordance', 'according', 'accordingly', 'across', 'act',
    'actually', 'ad', 'added', 'adj', 'adopted', 'ae', 'af', 'affected', 'affecting',
    'affects', 'afin', 'after', 'afterwards', 'ag', 'again', 'against', 'ago', 'ah', 'ahead',
    'ai', 'aie', 'aient', 'aies', 'ailleurs', "ain't", 'ainsi', 'aint', 'ait', 'al', 'all',
    'allaient', 'allo', 'allons', 'allow', 'allows', 'allô', 'almost', 'alone', 'along',
    'alongside', 'alors', 'already', 'also', 'although', 'always', 'am', 'amid', 'amidst',
    'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'announce', 'another', 'anterieur',
    'anterieure', 'anterieures', 'any', 'anybody', 'anyhow', 'anymore', 'anyone', 'anything',
    'anyway', 'anyways', 'anywhere', 'ao', 'apart', 'apparently', 'appear', 'appreciate',
    'appropriate', 'approximately', 'apres', 'après', 'aq', 'ar', 'are', 'area', 'areas',
    'aren', "aren't", 'arent', 'arise', 'around', 'arpa', 'as', 'aside', 'ask', 'asked',
    'asking', 'asks', 'assez', 'associated', 'at', 'attendu', 'au', 'aucun', 'aucune',
    'aucuns', 'aujourd', "aujourd'hui", 'aupres', 'auquel', 'aura', 'aurai', 'auraient',
    'aurais', 'aurait', 'auras', 'aurez', 'auriez', 'aurions', 'aurons', 'auront', 'aussi',
    'autant', 'auth', 'autre', 'autrefois', 'autrement', 'autres', 'autrui', 'aux',
    'auxquelles', 'auxquels', 'avaient', 'available', 'avais', 'avait', 'avant', 'avec',
    'avez', 'aviez', 'avions', 'avoir', 'avons', 'aw', 'away', 'awfully', 'ayant', 'ayez',
    'ayons', 'az', 'b', 'ba', 'back', 'backed', 'backing', 'backs', 'backward', 'backwards',
    'bah', 'bas', 'basee', 'bat', 'bb', 'bd', 'be', 'beau', 'beaucoup', 'became', 'because',
    'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'began', 'begin',
    'beginning', 'beginnings', 'begins', 'behind', 'being', 'beings', 'believe', 'below',
    'beside', 'besides', 'best', 'better', 'between', 'beyond', 'bf', 'bg', 'bh', 'bi', 'bien',
    'big', 'bigre', 'bill', 'billion', 'biol', 'bj', 'bm', 'bn', 'bo', 'bon', 'both', 'bottom',
    'boum', 'br', 'bravo', 'brief', 'briefly', 'brrr', 'bs', 'bt', 'but', 'buy', 'bv', 'bw',
    'by', 'bz', 'c', "c'mon", "c's", 'ca', 'call', 'came', 'can', "can't", 'cannot', 'cant',
    'caption', 'car', 'case', 'cases', 'cause', 'causes', 'cc', 'cd', 'ce', 'ceci', 'cela',
    'celle', 'celle-ci', 'celle-là', 'celles', 'celles-ci', 'celles-là', 'celui', 'celui-ci',
    'celui-là', 'celà', 'cent', 'cependant', 'certain', 'certaine', 'certaines', 'certainly',
    'certains', 'certes', 'ces', 'cet', 'cette', 'ceux', 'ceux-ci', 'ceux-là', 'cf', 'cg',
    'ch', 'chacun', 'chacune', 'changes', 'chaque', 'cher', 'chers', 'chez', 'chiche', 'chut',
    'chère', 'chères', 'ci', 'cinq', 'cinquantaine', 'cinquante', 'cinquantième', 'cinquième',
    'ck', 'cl', 'clac', 'clear', 'clearly', 'clic', 'click', 'cm', 'cmon', 'cn', 'co', 'co.',
    'com', 'combien', 'come', 'comes', 'comme', 'comment', 'comparable', 'comparables',
    'compris', 'computer', 'con', 'concernant', 'concerning', 'consequently', 'consider',
    'considering', 'contain', 'containing', 'contains', 'contre', 'copy', 'corresponding',
    'couic', 'could', "could've", 'couldn', "couldn't", 'couldnt', 'course', 'cr', 'crac',
    'cry', 'cs', 'cu', 'currently', 'cv', 'cx', 'cy', 'cz', 'd', 'da', 'dans', 'dare',
    "daren't", 'darent', 'date', 'de', 'dear', 'debout', 'dedans', 'definitely', 'dehors',
    'deja', 'delà', 'depuis', 'dernier', 'derniere', 'derriere', 'derrière', 'des', 'describe',
    'described', 'desormais', 'despite', 'desquelles', 'desquels', 'dessous', 'dessus',
    'detail', 'deux', 'deuxième', 'deuxièmement', 'devant', 'devers', 'devra', 'devrait',
    'did', 'didn', "didn't", 'didnt', 'differ', 'different', 'differentes', 'differently',
    'differents', 'différent', 'différente', 'différentes', 'différents', 'dire', 'directe',
    'directement', 'directly', 'dit', 'dite', 'dits', 'divers', 'diverse', 'diverses', 'dix',
    'dix-huit', 'dix-neuf', 'dix-sept', 'dixième', 'dj', 'dk', 'dm', 'do', 'does', 'doesn',
    "doesn't", 'doesnt', 'doing', 'doit', 'doivent', 'don', "don't", 'donc', 'done', 'dont',
    'dos', 'doubtful', 'douze', 'douzième', 'down', 'downed', 'downing', 'downs', 'downwards',
    'dring', 'droite', 'du', 'due', 'duquel', 'durant', 'during', 'dz', 'dès', 'début',
    'désormais', 'e', 'each', 'early', 'ec', 'ed', 'edu', 'ee', 'effect', 'effet', 'eg',
    'egale', 'egalement', 'egales', 'eh', 'eight', 'eighty', 'either', 'eleven', 'elle',
    'elle-même', 'elles', 'elles-mêmes', 'else', 'elsewhere', 'empty', 'en', 'encore', 'end',
    'ended', 'ending', 'ends', 'enfin', 'enough', 'entirely', 'entre', 'envers', 'environ',
    'er', 'es', 'especially', 'essai', 'est', 'et', 'et-al', 'etant', 'etc', 'etre', 'eu',
    'eue', 'eues', 'euh', 'eurent', 'eus', 'eusse', 'eussent', 'eusses', 'eussiez', 'eussions',
    'eut', 'eux', 'eux-mêmes', 'even', 'evenly', 'ever', 'evermore', 'every', 'everybody',
    'everyone', 'everything', 'everywhere', 'ex', 'exactement', 'exactly', 'example', 'except',
    'excepté', 'extenso', 'exterieur', 'eûmes', 'eût', 'eûtes', 'f', 'face', 'faces', 'fact',
    'facts', 'fairly', 'fais', 'faisaient', 'faisant', 'fait', 'faites', 'far', 'farther',
    'façon', 'felt', 'feront', 'few', 'fewer', 'ff', 'fi', 'fifteen', 'fifth', 'fifty', 'fify',
    'fill', 'find', 'finds', 'fire', 'first', 'five', 'fix', 'fj', 'fk', 'flac', 'floc', 'fm',
    'fo', 'fois', 'followed', 'following', 'follows', 'font', 'for', 'force', 'forever',
    'former', 'formerly', 'forth', 'forty', 'forward', 'found', 'four', 'fr', 'free', 'from',
    'front', 'full', 'fully', 'furent', 'further', 'furthered', 'furthering', 'furthermore',
    'furthers', 'fus', 'fusse', 'fussent', 'fusses', 'fussiez', 'fussions', 'fut', 'fx',
    'fûmes', 'fût', 'fûtes', 'g', 'ga', 'gave', 'gb', 'gd', 'ge', 'general', 'generally',
    'gens', 'get', 'gets', 'getting', 'gf', 'gg', 'gh', 'gi', 'give', 'given', 'gives',
    'giving', 'gl', 'gm', 'gmt', 'gn', 'go', 'goes', 'going', 'gone', 'good', 'goods', 'got',
    'gotten', 'gov', 'gp', 'gq', 'gr', 'great', 'greater', 'greatest', 'greetings', 'group',
    'grouped', 'grouping', 'groups', 'gs', 'gt', 'gu', 'gw', 'gy', 'h', 'ha', 'had', "hadn't",
    'hadnt', 'half', 'happens', 'hardly', 'has', 'hasn', "hasn't", 'hasnt', 'haut', 'have',
    'haven', "haven't", 'havent', 'having', 'he', "he'd", "he'll", "he's", 'hed', 'hein',
    'hell', 'hello', 'help', 'hem', 'hence', 'hep', 'her', 'here', "here's", 'hereafter',
    'hereby', 'herein', 'heres', 'hereupon', 'hers', 'herself', 'herse”', 'hes', 'hi', 'hid',
    'high', 'higher', 'highest', 'him', 'himself', 'himse”', 'his', 'hither', 'hk', 'hm', 'hn',
    'ho', 'holà', 'home', 'homepage', 'hop', 'hopefully', 'hormis', 'hors', 'hou', 'houp',
    'how', "how'd", "how'll", "how's", 'howbeit', 'however', 'hr', 'ht', 'htm', 'html', 'http',
    'hu', 'hue', 'hui', 'huit', 'huitième', 'hum', 'hundred', 'hurrah', 'hé', 'hélas', 'i',
    "i'd", "i'll", "i'm", "i've", 'i.e.', 'ici', 'id', 'ie', 'if', 'ignored', 'ii', 'il',
    'ill', 'ils', 'im', 'immediate', 'immediately', 'importance', 'important', 'importe', 'in',
    'inasmuch', 'inc', 'inc.', 'indeed', 'index', 'indicate', 'indicated', 'indicates',
    'information', 'inner', 'inside', 'insofar', 'instead', 'int', 'interest', 'interested',
    'interesting', 'interests', 'into', 'invention', 'inward', 'io', 'iq', 'ir', 'is', 'isn',
    "isn't", 'isnt', 'it', "it'd", "it'll", "it's", 'itd', 'itll', 'its', 'itself', 'itse”',
    'ive', 'j', 'je', 'jm', 'jo', 'join', 'jp', 'jusqu', 'jusque', 'just', 'juste', 'k', 'ke',
    'keep', 'keeps', 'kept', 'keys', 'kg', 'kh', 'ki', 'kind', 'km', 'kn', 'knew', 'know',
    'known', 'knows', 'kp', 'kr', 'kw', 'ky', 'kz', 'l', 'la', 'laisser', 'laquelle', 'large',
    'largely', 'las', 'last', 'lately', 'later', 'latest', 'latter', 'latterly', 'lb', 'lc',
    'le', 'least', 'length', 'lequel', 'les', 'lesquelles', 'lesquels', 'less', 'lest', 'let',
    "let's", 'lets', 'leur', 'leurs', 'li', 'like', 'liked', 'likely', 'likewise', 'line',
    'little', 'lk', 'll', 'long', 'longer', 'longest', 'longtemps', 'look', 'looking', 'looks',
    'lors', 'lorsque', 'low', 'lower', 'lr', 'ls', 'lt', 'ltd', 'lu', 'lui', 'lui-meme',
    'lui-même', 'lv', 'ly', 'là', 'lès', 'm', 'ma', 'made', 'mainly', 'maint', 'maintenant',
    'mais', 'make', 'makes', 'making', 'malgre', 'malgré', 'man', 'many', 'maximale', 'may',
    'maybe', "mayn't", 'maynt', 'mc', 'md', 'me', 'mean', 'means', 'meantime', 'meanwhile',
    'member', 'members', 'meme', 'memes', 'men', 'merci', 'merely', 'mes', 'mg', 'mh',
    'microsoft', 'mien', 'mienne', 'miennes', 'miens', 'might', "might've", "mightn't",
    'mightnt', 'mil', 'mill', 'mille', 'million', 'mince', 'mine', 'minimale', 'minus', 'miss',
    'mk', 'ml', 'mm', 'mn', 'mo', 'moi', 'moi-meme', 'moi-même', 'moindres', 'moins', 'mon',
    'more', 'moreover', 'most', 'mostly', 'mot', 'move', 'moyennant', 'mp', 'mq', 'mr', 'mrs',
    'ms', 'msie', 'mt', 'mu', 'much', 'mug', 'multiple', 'multiples', 'must', "must've",
    "mustn't", 'mustnt', 'mv', 'mw', 'mx', 'my', 'myself', 'myse”', 'mz', 'même', 'mêmes', 'n',
    'na', 'name', 'namely', 'naturel', 'naturelle', 'naturelles', 'nay', 'nc', 'nd', 'ne',
    'neanmoins', 'near', 'nearly', 'necessaire', 'necessairement', 'necessarily', 'necessary',
    'need', 'needed', 'needing', "needn't", 'neednt', 'needs', 'neither', 'net', 'netscape',
    'neuf', 'neuvième', 'never', 'neverf', 'neverless', 'nevertheless', 'new', 'newer',
    'newest', 'next', 'nf', 'ng', 'ni', 'nine', 'ninety', 'nl', 'no', 'no-one', 'nobody',
    'nombreuses', 'nombreux', 'nommés', 'non', 'none', 'nonetheless', 'noone', 'nor',
    'normally', 'nos', 'not', 'notamment', 'noted', 'nothing', 'notre', 'notwithstanding',
    'nous', 'nous-mêmes', 'nouveau', 'nouveaux', 'novel', 'now', 'nowhere', 'np', 'nr', 'nu',
    'nul', 'null', 'number', 'numbers', 'nz', 'néanmoins', 'nôtre', 'nôtres', 'o', 'obtain',
    'obtained', 'obviously', 'of', 'off', 'often', 'oh', 'ohé', 'ok', 'okay', 'old', 'older',
    'oldest', 'ollé', 'olé', 'om', 'omitted', 'on', 'once', 'one', "one's", 'ones', 'only',
    'ont', 'onto', 'onze', 'onzième', 'open', 'opened', 'opening', 'opens', 'opposite', 'or',
    'ord', 'order', 'ordered', 'ordering', 'orders', 'ore', 'org', 'other', 'others',
    'otherwise', 'ou', 'ouf', 'ought', "oughtn't", 'oughtnt', 'ouias', 'our', 'ours',
    'ourselves', 'oust', 'ouste', 'out', 'outre', 'outside', 'ouvert', 'ouverte', 'ouverts',
    'over', 'overall', 'owing', 'own', 'o|', 'où', 'p', 'pa', 'paf', 'page', 'pages', 'pan',
    'par', 'parce', 'parfois', 'parle', 'parlent', 'parler', 'parmi', 'parole', 'parseme',
    'part', 'partant', 'parted', 'particular', 'particularly', 'particulier', 'particulière',
    'particulièrement', 'parting', 'parts', 'pas', 'passé', 'past', 'pe', 'pendant', 'pense',
    'per', 'perhaps', 'permet', 'personne', 'personnes', 'peu', 'peut', 'peuvent', 'peux',
    'pf', 'pff', 'pfft', 'pfut', 'pg', 'ph', 'pif', 'pire', 'pièce', 'pk', 'pl', 'place',
    'placed', 'places', 'please', 'plein', 'plouf', 'plupart', 'plus', 'plusieurs', 'plutôt',
    'pm', 'pmid', 'pn', 'point', 'pointed', 'pointing', 'points', 'poorly', 'possessif',
    'possessifs', 'possible', 'possibles', 'possibly', 'potentially', 'pouah', 'pour',
    'pourquoi', 'pourrais', 'pourrait', 'pouvait', 'pp', 'pr', 'prealable', 'precisement',
    'predominantly', 'premier', 'première', 'premièrement', 'pres', 'present', 'presented',
    'presenting', 'presents', 'presumably', 'previously', 'primarily', 'probable', 'probably',
    'probante', 'problem', 'problems', 'procedant', 'proche', 'promptly', 'proud', 'provided',
    'provides', 'près', 'psitt', 'pt', 'pu', 'puis', 'puisque', 'pur', 'pure', 'put', 'puts',
    'pw', 'py', 'q', 'qa', 'qu', 'quand', 'quant', 'quant-à-soi', 'quanta', 'quarante',
    'quatorze', 'quatre', 'quatre-vingt', 'quatrième', 'quatrièmement', 'que', 'quel',
    'quelconque', 'quelle', 'quelles', "quelqu'un", 'quelque', 'quelques', 'quels', 'qui',
    'quickly', 'quiconque', 'quinze', 'quite', 'quoi', 'quoique', 'qv', 'r', 'ran', 'rare',
    'rarement', 'rares', 'rather', 'rd', 're', 'readily', 'really', 'reasonably', 'recent',
    'recently', 'ref', 'refs', 'regarding', 'regardless', 'regards', 'related', 'relative',
    'relatively', 'relativement', 'remarquable', 'rend', 'rendre', 'research', 'reserved',
    'respectively', 'restant', 'reste', 'restent', 'restrictif', 'resulted', 'resulting',
    'results', 'retour', 'revoici', 'revoilà', 'rien', 'right', 'ring', 'ro', 'room', 'rooms',
    'round', 'ru', 'run', 'rw', 's', 'sa', 'sacrebleu', 'said', 'sait', 'same', 'sans',
    'sapristi', 'sauf', 'saw', 'say', 'saying', 'says', 'sb', 'sc', 'sd', 'se', 'sec',
    'second', 'secondly', 'seconds', 'section', 'see', 'seeing', 'seem', 'seemed', 'seeming',
    'seems', 'seen', 'sees', 'sein', 'seize', 'self', 'selon', 'selves', 'semblable',
    'semblaient', 'semble', 'semblent', 'sensible', 'sent', 'sept', 'septième', 'sera',
    'serai', 'seraient', 'serais', 'serait', 'seras', 'serez', 'seriez', 'serions', 'serious',
    'seriously', 'serons', 'seront', 'ses', 'seul', 'seule', 'seulement', 'seven', 'seventy',
    'several', 'sg', 'sh', 'shall', "shan't", 'shant', 'she', "she'd", "she'll", "she's",
    'shed', 'shell', 'shes', 'should', "should've", 'shouldn', "shouldn't", 'shouldnt', 'show',
    'showed', 'showing', 'shown', 'showns', 'shows', 'si', 'side', 'sides', 'sien', 'sienne',
    'siennes', 'siens', 'significant', 'significantly', 'similar', 'similarly', 'since',
    'sincere', 'sinon', 'site', 'six', 'sixième', 'sixty', 'sj', 'sk', 'sl', 'slightly', 'sm',
    'small', 'smaller', 'smallest', 'sn', 'so', 'soi', 'soi-même', 'soient', 'sois', 'soit',
    'soixante', 'some', 'somebody', 'someday', 'somehow', 'someone', 'somethan', 'something',
    'sometime', 'sometimes', 'somewhat', 'somewhere', 'sommes', 'son', 'sont', 'soon', 'sorry',
    'sous', 'souvent', 'soyez', 'soyons', 'specifically', 'specified', 'specifique',
    'specifiques', 'specify', 'specifying', 'speculatif', 'sr', 'st', 'state', 'states',
    'still', 'stop', 'strictement', 'strongly', 'su', 'sub', 'substantially', 'subtiles',
    'successfully', 'such', 'sufficiently', 'suffisant', 'suffisante', 'suffit', 'suggest',
    'suis', 'suit', 'suivant', 'suivante', 'suivantes', 'suivants', 'suivre', 'sujet', 'sup',
    'superpose', 'sur', 'sure', 'surtout', 'sv', 'sy', 'system', 'sz', 't', "t's", 'ta', 'tac',
    'take', 'taken', 'taking', 'tandis', 'tant', 'tardive', 'tc', 'td', 'te', 'tel', 'tell',
    'telle', 'tellement', 'telles', 'tels', 'ten', 'tenant', 'tend', 'tends', 'tenir', 'tente',
    'tes', 'test', 'text', 'tf', 'tg', 'th', 'than', 'thank', 'thanks', 'thanx', 'that',
    "that'll", "that's", "that've", 'thatll', 'thats', 'thatve', 'the', 'their', 'theirs',
    'them', 'themselves', 'then', 'thence', 'there', "there'd", "there'll", "there're",
    "there's", "there've", 'thereafter', 'thereby', 'thered', 'therefore', 'therein',
    'therell', 'thereof', 'therere', 'theres', 'thereto', 'thereupon', 'thereve', 'these',
    'they', "they'd", "they'll", "they're", "they've", 'theyd', 'theyll', 'theyre', 'theyve',
    'thick', 'thin', 'thing', 'things', 'think', 'thinks', 'third', 'thirty', 'this',
    'thorough', 'thoroughly', 'those', 'thou', 'though', 'thoughh', 'thought', 'thoughts',
    'thousand', 'three', 'throug', 'through', 'throughout', 'thru', 'thus', 'tic', 'tien',
    'tienne', 'tiennes', 'tiens', 'til', 'till', 'tip', 'tis', 'tj', 'tk', 'tm', 'tn', 'to',
    'toc', 'today', 'together', 'toi', 'toi-même', 'ton', 'too', 'took', 'top', 'touchant',
    'toujours', 'tous', 'tout', 'toute', 'toutefois', 'toutes', 'toward', 'towards', 'tp',
    'tr', 'treize', 'trente', 'tres', 'tried', 'tries', 'trillion', 'trois', 'troisième',
    'troisièmement', 'trop', 'truly', 'try', 'trying', 'très', 'ts', 'tsoin', 'tsouin', 'tt',
    'tu', 'turn', 'turned', 'turning', 'turns', 'tv', 'tw', 'twas', 'twelve', 'twenty',
    'twice', 'two', 'tz', 'té', 'u', 'ua', 'ug', 'uk', 'um', 'un', 'under', 'underneath',
    'undoing', 'une', 'unes', 'unfortunately', 'uniformement', 'unique', 'uniques', 'unless',
    'unlike', 'unlikely', 'uns', 'until', 'unto', 'up', 'upon', 'ups', 'upwards', 'us', 'use',
    'used', 'useful', 'usefully', 'usefulness', 'uses', 'using', 'usually', 'uucp', 'uy', 'uz',
    'v', 'va', 'vais', 'valeur', 'value', 'various', 'vas', 'vc', 've', 'vers', 'versus',
    'very', 'vg', 'vi', 'via', 'vif', 'vifs', 'vingt', 'vivat', 'vive', 'vives', 'viz', 'vlan',
    'vn', 'voici', 'voie', 'voient', 'voilà', 'voire', 'vol', 'vols', 'vont', 'vos', 'votre',
    'vous', 'vous-mêmes', 'vs', 'vu', 'vé', 'vôtre', 'vôtres', 'w', 'want', 'wanted',
    'wanting', 'wants', 'was', 'wasn', "wasn't", 'wasnt', 'way', 'ways', 'we', "we'd", "we'll",
    "we're", "we've", 'web', 'webpage', 'website', 'wed', 'welcome', 'well', 'wells', 'went',
    'were', 'weren', "weren't", 'werent', 'weve', 'wf', 'what', "what'd", "what'll", "what's",
    "what've", 'whatever', 'whatll', 'whats', 'whatve', 'when', "when'd", "when'll", "when's",
    'whence', 'whenever', 'where', "where'd", "where'll", "where's", 'whereafter', 'whereas',
    'whereby', 'wherein', 'wheres', 'whereupon', 'wherever', 'whether', 'which', 'whichever',
    'while', 'whilst', 'whim', 'whither', 'who', "who'd", "who'll", "who's", 'whod', 'whoever',
    'whole', 'wholl', 'whom', 'whomever', 'whos', 'whose', 'why', "why'd", "why'll", "why's",
    'widely', 'width', 'will', 'willing', 'wish', 'with', 'within', 'without', 'won', "won't",
    'wonder', 'wont', 'words', 'work', 'worked', 'working', 'works', 'world', 'would',
    "would've", 'wouldn', "wouldn't", 'wouldnt', 'ws', 'www', 'x', 'y', 'ye', 'year', 'years',
    'yes', 'yet', 'you', "you'd", "you'll", "you're", "you've", 'youd', 'youll', 'young',
    'younger', 'youngest', 'your', 'youre', 'yours', 'yourself', 'yourselves', 'youve', 'yt',
    'yu', 'z', 'za', 'zero', 'zm', 'zr', 'zut', 'à', 'â', 'ça', 'ès', 'étaient', 'étais',
    'était', 'étant', 'état', 'étiez', 'étions', 'été', 'étée', 'étées', 'étés', 'êtes',
    'être', 'ô',
})
